### ISSUE TITLE
про data классы и конструкторы

### ISSUE THREAD

**Issue by 2ZeroSix** [LogchainApp/Logchain#1]
https://github.com/LogchainApp/Logchain/blob/87667713372cc56fea114e5ff820a342a13304da/lib/models/Period.dart#L3-L10

- не стоит использовать late без необходимости, присваивать в конструкторе в final поля можно:
  -  указывая аргументы с `this.<name>` синтаксисом (как здесь и сделано)
  -  с помощью [списка инициализации](https://dart.dev/guides/language/language-tour#initializer-list), это полезно для вычисляемых значений и для полей отличающихся названием от аргумента (например оно приватное, а аргумент именованный) 
- в конструкторе не нужно дублировать тип при инициализации полей через this, он уже указан на самом поле. [type_init_formals](https://dart-lang.github.io/linter/lints/type_init_formals.html)
- в data классах (без изменяемых полей) рекомендуется делать const конструктор. [prefer_const_constructors_in_immutables](https://dart-lang.github.io/linter/lints/prefer_const_constructors_in_immutables.html) (к сожалению оно работает только если явно указывать аннотацию [@immutable](https://api.flutter.dev/flutter/meta/immutable-constant.html), но если решите использовать [freezed](https://pub.dev/packages/freezed), то он проставляет ее в сгенерированном коде)
- не оставляйте пустые тела в конструкторах. [empty_constructor_bodies](https://dart-lang.github.io/linter/lints/empty_constructor_bodies.html)

**Comment by egor-baranov** [comment]
Done
