### ISSUE TITLE
top-level/static 

### ISSUE THREAD

**Issue by 2ZeroSix** [LogchainApp/Logchain#2]
https://github.com/LogchainApp/Logchain/blob/87667713372cc56fea114e5ff820a342a13304da/lib/styles/TextStyles.dart#L11-L27

Нет необходимости в использовании late в статических и top-level переменных, если они инициализируются сразу при объявлении. Они по-умолчанию инициализируются при первом обращении

https://dart.dev/guides/language/language-tour#default-value

**Comment by egor-baranov** [comment]
Пофиксил
