### ISSUE TITLE
Передавайте виджеты

### ISSUE THREAD

**Issue by 2ZeroSix** [LogchainApp/Logchain#4]
Метод с title в виде строки здесь не нужен, а даже вреден. Подобный код приводит к проблемам при добавлении в приложение локализации
- прокинули строку на одном языке
- сменили язык
- строка осталась старой

https://github.com/LogchainApp/Logchain/blob/87667713372cc56fea114e5ff820a342a13304da/lib/widgets/BottomDialog.dart#L9-L14

чтобы достичь эффекта со стилем по-умолчанию можно использовать виджет DefaultTextStyle

**Comment by egor-baranov** [comment]
Done
