### ISSUE TITLE
вред Stateful виджетов aka unidirectional data flow

### ISSUE THREAD

**Issue by 2ZeroSix** [LogchainApp/Logchain#5]
Старайтесь использовать Stateful виджеты по минимуму:
- контроль ui состояния: анимаций, скролл контроллеров итд
- корень приложения
- иногда корень страницы
- другие редкие исключения

https://github.com/LogchainApp/Logchain/blob/87667713372cc56fea114e5ff820a342a13304da/lib/widgets/DatePicker.dart#L45-L52

Такой код может быть как удобным, так и приводить к проблемам.
Конкретно здесь мы лишаемся контроля над состоянием фильтра снаружи, контроль над этим состоянием остается целиком на стейте виджета.

В итоге состояние начинает течь в обратную сторону, усложняется контроль над состоянием приложения.
Для коннекта с UDF архитектурами приходится городить костыли (например открытие стейта наружу и обращение к нему через `GlobalKey::currentState`)

Что здесь может хорошо подойти:
- передавать в виджет `ValueNotifier` через конструктор
- никак не контролировать смену элемента внутри виджета, только сообщать через колбек, а значение получать через `ValueListenable`
  - не значение напрямую а обертку в виде `ValueListenable` как раз чтобы иметь возможность пересобирать части дерева только при реальной необходимости
  
Что могло бы подойти, но не стоит
- другие реактивные подходы (стримы/rx)
  - явный оверкилл для такой простой задачи
- подходы с взятием значений из контекста (provider, riverpod, обертки из полноценных стейт менеджеров)
  - делают api виджета неявным
    - хорошо подходит для проброса информации глубоко в дерево
    - плохо подходит для базовых ui компонентов

далее поверх этого можно оптимизировать перестроение дерева, чтобы не пересоздавать весь список при изменении выбора

**Comment by egor-baranov** [comment]
Отрефакторил с RX:
Callback из FilterWidget и PeriodPicker в stateless CustomAppBar, а оттуда в stateful MainPanel, откуда и производится менеджмент стейтов и коллбеков (хранится глобальная сотрировка ленты и выбранный временной промежуток). Провайдеры у нас тоже есть в папке providers, но они пока в процессе разработки
